# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78a43e35139b4867863bdf43f07b8f88c1b07f996924541f5ca87ae183a1106face8102ff4cc926fd76999d93c255e2da018003e6a94969afdb47af213fb708

test:
  secret_key_base: bb26487f8393a21f91d1bd4d1c4de0c0d41f815ce9445c9f831b1be9255fc6629ab07439fdcb13e29f3c23b8bf61a55f91826a87bab9c25b583f34a133f5abea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
